close all; clear all; clc;
width = 600;
response_size = width*[1, 1.3/1.5];
control_size = width*[1, 1.3];
plotColor = orderedcolors('gem');
bold_width = 1.5;
line_width = 1.5;
font_size = 12;
% load('logs\morphing_mk2_log_delay0_3.mat');

% [pos_n, pos_e, pos_d] = deal(X(:, 1), X(:, 2), X(:, 3));
% [ref_pn, ref_pe, ref_pd] = deal(2*ones([length(t), 1]), 2*ones([length(t), 1]), -2*ones([length(t), 1]));
% Posplot = figure();
% Posplot.Theme = 'light';
% Posplot.Position(3:4) = response_size;
% subplot(3, 1, 1);
% subtitle('Position response of MAS in X-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% res_pn_plot = plot(t, pos_n, 'Color', plotColor(1,:), 'LineWidth', line_width);
% cmd_pn_plot = plot(t, ref_pn, 'r--', 'LineWidth', line_width);
% ylabel('$r_n$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
% legend([cmd_pn_plot, res_pn_plot], {'Command', 'Response'}, 'Interpreter', 'latex', 'Location', 'southeast');
% subplot(3, 1, 2);
% hold on; grid on;
% plot(t, pos_e, 'Color', plotColor(1,:), 'LineWidth', line_width);
% plot(t, ref_pe, 'r--', 'LineWidth', line_width);
% ylabel('$r_e$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(3, 1, 3);
% hold on; grid on;
% plot(t, pos_d, 'Color', plotColor(1,:), 'LineWidth', line_width);
% plot(t, ref_pd, 'r--', 'LineWidth', line_width);
% ylabel('$r_d$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figPositionResponse_x.png', '-dpng', '-r500');
% 
% [att_r, att_p, att_y] = deal(rad2deg(X(:, 10)), rad2deg(X(:, 11)), rad2deg(X(:, 12)));
% [ref_r, ref_p, ref_y] = deal(20*ones([length(t), 1]), 30*ones([length(t), 1]), zeros([length(t), 1]));
% AttPlot = figure();
% AttPlot.Theme = 'light';
% AttPlot.Position(3:4) = response_size;
% subplot(3, 1, 1);
% subtitle('Attitude response of MAS in X-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% res_r_plot = plot(t, att_r, 'Color', plotColor(1, :), 'LineWidth', line_width);
% cmd_r_plot = plot(t, ref_r, 'r--', 'LineWidth', line_width);
% ylabel('$\phi$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% legend([cmd_r_plot, res_r_plot], {'Command', 'Response'}, 'Interpreter', 'latex', 'Location', 'southeast');
% subplot(3, 1, 2);
% hold on; grid on;
% plot(t, att_p, 'Color', plotColor(1, :), 'LineWidth', line_width);
% plot(t, ref_p, 'r--', 'LineWidth', line_width);
% ylabel('$\theta$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(3, 1, 3);
% hold on; grid on;
% plot(t, att_y, 'Color', plotColor(1, :), 'LineWidth', line_width);
% plot(t, ref_y, 'r--', 'LineWidth', line_width);
% ylabel('$\psi$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figAttitudeResponse_x.png', '-dpng', '-r500');
% 
% PropPlot = figure();
% PropPlot.Theme = 'light';
% PropPlot.Position(3:4) = control_size;
% subplot(4, 1, 1);
% subtitle('Rotor Angular Speed of MAS in X-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% plot(t, Wm(:, 1), 'LineWidth', line_width);
% ylabel('$\omega_1^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 2);
% hold on; grid on;
% plot(t, Wm(:, 2), 'LineWidth', line_width);
% ylabel('$\omega_2^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 3);
% hold on; grid on;
% plot(t, Wm(:, 3), 'LineWidth', line_width);
% ylabel('$\omega_3^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 4);
% hold on; grid on;
% plot(t, Wm(:, 4), 'LineWidth', line_width);
% ylabel('$\omega_4^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figRotorAngularSpeed_x.png', '-dpng', '-r500');
% 
% FlarePlot = figure();
% FlarePlot.Theme = 'light';
% FlarePlot.Position(3:4) = control_size;
% subplot(4, 1, 1);
% subtitle('Flare angles of MAS in X-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% plot(t, rad2deg(Alpha(:, 1)), 'LineWidth', line_width);
% ylabel('$\alpha_1$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 2);
% hold on; grid on;
% plot(t, rad2deg(Alpha(:, 2)), 'LineWidth', line_width);
% ylabel('$\alpha_2$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 3);
% hold on; grid on;
% plot(t, rad2deg(Alpha(:, 3)), 'LineWidth', line_width);
% ylabel('$\alpha_3$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 4);
% hold on; grid on;
% plot(t, rad2deg(Alpha(:, 4)), 'LineWidth', line_width);
% ylabel('$\alpha_4$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figFlareAngles_x.png', '-dpng', '-r500');
% 
% TiltPlot = figure();
% TiltPlot.Theme = 'light';
% TiltPlot.Position(3:4) = control_size;
% subplot(4, 1, 1);
% subtitle('Tilt angles of MAS in X-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% plot(t, rad2deg(Beta(:, 1)), 'LineWidth', line_width);
% ylabel('$\beta_1$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 2);
% hold on; grid on;
% plot(t, rad2deg(Beta(:, 2)), 'LineWidth', line_width);
% ylabel('$\beta_2$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 3);
% hold on; grid on;
% plot(t, rad2deg(Beta(:, 3)), 'LineWidth', line_width);
% ylabel('$\beta_3$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 4);
% hold on; grid on;
% plot(t, rad2deg(Beta(:, 4)), 'LineWidth', line_width);
% ylabel('$\beta_4$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figTiltAngles_x.png', '-dpng', '-r500');

%%
noDelay = load('logs\data_delay\morphing_mk2_log_0_00_instant_detect.mat');
Delay005 = load('logs\data_delay\morphing_mk2_log_0_05.mat');
Delay010 = load('logs\data_delay\morphing_mk2_log_0_10.mat');
Delay015 = load('logs\data_delay\morphing_mk2_log_0_15.mat');
Delay020 = load('logs\data_delay\morphing_mk2_log_0_20.mat');
Delay025 = load('logs\data_delay\morphing_mk2_log_0_25.mat');
Delay030 = load('logs\data_delay\morphing_mk2_log_0_30.mat');
Delay035 = load('logs\data_delay\morphing_mk2_log_0_35.mat');
Delay040 = load('logs\data_delay\morphing_mk2_log_0_40.mat');
Delay045 = load('logs\data_delay\morphing_mk2_log_0_45.mat');
Delay050 = load('logs\data_delay\morphing_mk2_log_0_50.mat');

PosCmprsnPlot = figure();
PosCmprsnPlot.Theme = 'light';
PosCmprsnPlot.Position(3:4) = response_size;
subplot(3, 1, 1);
hold on; grid on;
plot(noDelay.t, noDelay.X(:, 1), 'LineWidth', line_width);
plot(Delay005.t, Delay005.X(:, 1), 'LineWidth', line_width);
plot(Delay010.t, Delay010.X(:, 1), 'LineWidth', line_width);
plot(Delay015.t, Delay015.X(:, 1), 'LineWidth', line_width);
plot(Delay020.t, Delay020.X(:, 1), 'LineWidth', line_width);
plot(Delay025.t, Delay025.X(:, 1), 'LineWidth', line_width);
plot(Delay030.t, Delay030.X(:, 1), 'LineWidth', line_width);
plot(Delay035.t, Delay035.X(:, 1), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, Delay040.X(:, 1), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, Delay045.X(:, 1), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, Delay050.X(:, 1), 'LineWidth', line_width, 'LineStyle', '-.');
ylim([-0.5, 4]);
ylabel('$r_n$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(3, 1, 2);
hold on; grid on;
plot(noDelay.t, noDelay.X(:, 2), 'LineWidth', line_width);
plot(Delay005.t, Delay005.X(:, 2), 'LineWidth', line_width);
plot(Delay010.t, Delay010.X(:, 2), 'LineWidth', line_width);
plot(Delay015.t, Delay015.X(:, 2), 'LineWidth', line_width);
plot(Delay020.t, Delay020.X(:, 2), 'LineWidth', line_width);
plot(Delay025.t, Delay025.X(:, 2), 'LineWidth', line_width);
plot(Delay030.t, Delay030.X(:, 2), 'LineWidth', line_width);
plot(Delay035.t, Delay035.X(:, 2), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, Delay040.X(:, 2), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, Delay045.X(:, 2), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, Delay050.X(:, 2), 'LineWidth', line_width, 'LineStyle', '-.');
ylim([-0.5, 4]);
ylabel('$r_e$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(3, 1, 3);
hold on; grid on;
plot(noDelay.t, noDelay.X(:, 3), 'LineWidth', line_width);
plot(Delay005.t, Delay005.X(:, 3), 'LineWidth', line_width);
plot(Delay010.t, Delay010.X(:, 3), 'LineWidth', line_width);
plot(Delay015.t, Delay015.X(:, 3), 'LineWidth', line_width);
plot(Delay020.t, Delay020.X(:, 3), 'LineWidth', line_width);
plot(Delay025.t, Delay025.X(:, 3), 'LineWidth', line_width);
plot(Delay030.t, Delay030.X(:, 3), 'LineWidth', line_width);
plot(Delay035.t, Delay035.X(:, 3), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, Delay040.X(:, 3), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, Delay045.X(:, 3), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, Delay050.X(:, 3), 'LineWidth', line_width, 'LineStyle', '-.');
ylim([-3, 0.5]);
ylabel('$r_d$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
print(PosCmprsnPlot, 'image/time_delay/fig_position_comparison_td', '-dpng', '-r600');

AttCmprsnPlot = figure();
AttCmprsnPlot.Theme = 'light';
AttCmprsnPlot.Position(3:4) = response_size;
subplot(3, 1, 1);
hold on; grid on;
plot(noDelay.t, rad2deg(noDelay.X(:, 10)), 'LineWidth', line_width);
plot(Delay005.t, rad2deg(Delay005.X(:, 10)), 'LineWidth', line_width);
plot(Delay010.t, rad2deg(Delay010.X(:, 10)), 'LineWidth', line_width);
plot(Delay015.t, rad2deg(Delay015.X(:, 10)), 'LineWidth', line_width);
plot(Delay020.t, rad2deg(Delay020.X(:, 10)), 'LineWidth', line_width);
plot(Delay025.t, rad2deg(Delay025.X(:, 10)), 'LineWidth', line_width);
plot(Delay030.t, rad2deg(Delay030.X(:, 10)), 'LineWidth', line_width);
plot(Delay035.t, rad2deg(Delay035.X(:, 10)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, rad2deg(Delay040.X(:, 10)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, rad2deg(Delay045.X(:, 10)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, rad2deg(Delay050.X(:, 10)), 'LineWidth', line_width, 'LineStyle', '-.');
ylim([-150, 75]);
ylabel('$\phi$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(3, 1, 2);
hold on; grid on;
plot(noDelay.t, rad2deg(noDelay.X(:, 11)), 'LineWidth', line_width);
plot(Delay005.t, rad2deg(Delay005.X(:, 11)), 'LineWidth', line_width);
plot(Delay010.t, rad2deg(Delay010.X(:, 11)), 'LineWidth', line_width);
plot(Delay015.t, rad2deg(Delay015.X(:, 11)), 'LineWidth', line_width);
plot(Delay020.t, rad2deg(Delay020.X(:, 11)), 'LineWidth', line_width);
plot(Delay025.t, rad2deg(Delay025.X(:, 11)), 'LineWidth', line_width);
plot(Delay030.t, rad2deg(Delay030.X(:, 11)), 'LineWidth', line_width);
plot(Delay035.t, rad2deg(Delay035.X(:, 11)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, rad2deg(Delay040.X(:, 11)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, rad2deg(Delay045.X(:, 11)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, rad2deg(Delay050.X(:, 11)), 'LineWidth', line_width, 'LineStyle', '-.');
ylim([-90, 20]);
ylabel('$\theta$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(3, 1, 3);
hold on; grid on;
index_00 = plot(noDelay.t, rad2deg(noDelay.X(:, 12)), 'LineWidth', line_width);
index_05 = plot(Delay005.t, rad2deg(Delay005.X(:, 12)), 'LineWidth', line_width);
index_10 = plot(Delay010.t, rad2deg(Delay010.X(:, 12)), 'LineWidth', line_width);
index_15 = plot(Delay015.t, rad2deg(Delay015.X(:, 12)), 'LineWidth', line_width);
index_20 = plot(Delay020.t, rad2deg(Delay020.X(:, 12)), 'LineWidth', line_width);
index_25 = plot(Delay025.t, rad2deg(Delay025.X(:, 12)), 'LineWidth', line_width);
index_30 = plot(Delay030.t, rad2deg(Delay030.X(:, 12)), 'LineWidth', line_width);
index_35 = plot(Delay035.t, rad2deg(Delay035.X(:, 12)), 'LineWidth', line_width, 'LineStyle', '-.');
index_40 = plot(Delay040.t, rad2deg(Delay040.X(:, 12)), 'LineWidth', line_width, 'LineStyle', '-.');
index_45 = plot(Delay045.t, rad2deg(Delay045.X(:, 12)), 'LineWidth', line_width, 'LineStyle', '-.');
index_50 = plot(Delay050.t, rad2deg(Delay050.X(:, 12)), 'LineWidth', line_width, 'LineStyle', '-.');
ylim([0, 180]);
ylabel('$\psi$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
legend([index_00, index_05, index_10, index_15, index_20, index_25, index_30, index_35, index_40, index_45, index_50],...
       {'No Delay', '0.05s', '0.10s', '0.15s', '0.20s', '0.25s',...
       '0.30s', '0.35s', '0.40s', '0.45s', '0.50s'},...
       'Location', 'northwest', 'Interpreter', 'latex', 'FontSize', 5, 'FontWeight','bold');
print(AttCmprsnPlot, 'image/time_delay/fig_attitude_comparison_td', '-dpng', '-r600');

PropCmprsnPlot = figure();
PropCmprsnPlot.Theme = 'light';
PropCmprsnPlot.Position(3:4) = control_size;
subplot(4, 1, 1);
hold on; grid on;
index_00 = plot(noDelay.t, noDelay.Wm(:, 1), 'LineWidth', line_width);
index_05 = plot(Delay005.t, Delay005.Wm(:, 1), 'LineWidth', line_width);
index_10 = plot(Delay010.t, Delay010.Wm(:, 1), 'LineWidth', line_width);
index_15 = plot(Delay015.t, Delay015.Wm(:, 1), 'LineWidth', line_width);
index_20 = plot(Delay020.t, Delay020.Wm(:, 1), 'LineWidth', line_width);
index_25 = plot(Delay025.t, Delay025.Wm(:, 1), 'LineWidth', line_width);
index_30 = plot(Delay030.t, Delay030.Wm(:, 1), 'LineWidth', line_width);
index_35 = plot(Delay035.t, Delay035.Wm(:, 1), 'LineWidth', line_width, 'LineStyle', '-.');
index_40 = plot(Delay040.t, Delay040.Wm(:, 1), 'LineWidth', line_width, 'LineStyle', '-.');
index_45 = plot(Delay045.t, Delay045.Wm(:, 1), 'LineWidth', line_width, 'LineStyle', '-.');
index_50 = plot(Delay050.t, Delay050.Wm(:, 1), 'LineWidth', line_width, 'LineStyle', '-.');
ylabel('$\omega_1^2$ $($rad/s$)^2$', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(4, 1, 2);
hold on; grid on;
plot(noDelay.t, noDelay.Wm(:, 2), 'LineWidth', line_width);
plot(Delay005.t, Delay005.Wm(:, 2), 'LineWidth', line_width);
plot(Delay010.t, Delay010.Wm(:, 2), 'LineWidth', line_width);
plot(Delay015.t, Delay015.Wm(:, 2), 'LineWidth', line_width);
plot(Delay020.t, Delay020.Wm(:, 2), 'LineWidth', line_width);
plot(Delay025.t, Delay025.Wm(:, 2), 'LineWidth', line_width);
plot(Delay030.t, Delay030.Wm(:, 2), 'LineWidth', line_width);
plot(Delay035.t, Delay035.Wm(:, 2), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, Delay040.Wm(:, 2), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, Delay045.Wm(:, 2), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, Delay050.Wm(:, 2), 'LineWidth', line_width, 'LineStyle', '-.');
ylim([0, 4.5]);
ylabel('$\omega_2^2$ $($rad/s$)^2$', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(4, 1, 3);
hold on; grid on;
plot(noDelay.t, noDelay.Wm(:, 3), 'LineWidth', line_width);
plot(Delay005.t, Delay005.Wm(:, 3), 'LineWidth', line_width);
plot(Delay010.t, Delay010.Wm(:, 3), 'LineWidth', line_width);
plot(Delay015.t, Delay015.Wm(:, 3), 'LineWidth', line_width);
plot(Delay020.t, Delay020.Wm(:, 3), 'LineWidth', line_width);
plot(Delay025.t, Delay025.Wm(:, 3), 'LineWidth', line_width);
plot(Delay030.t, Delay030.Wm(:, 3), 'LineWidth', line_width);
plot(Delay035.t, Delay035.Wm(:, 3), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, Delay040.Wm(:, 3), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, Delay045.Wm(:, 3), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, Delay050.Wm(:, 3), 'LineWidth', line_width, 'LineStyle', '-.');
ylim([-0.5, 2.5]);
ylabel('$\omega_3^2$ $($rad/s$)^2$', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(4, 1, 4);
hold on; grid on;
plot(noDelay.t, noDelay.Wm(:, 4), 'LineWidth', line_width);
plot(Delay005.t, Delay005.Wm(:, 4), 'LineWidth', line_width);
plot(Delay010.t, Delay010.Wm(:, 4), 'LineWidth', line_width);
plot(Delay015.t, Delay015.Wm(:, 4), 'LineWidth', line_width);
plot(Delay020.t, Delay020.Wm(:, 4), 'LineWidth', line_width);
plot(Delay025.t, Delay025.Wm(:, 4), 'LineWidth', line_width);
plot(Delay030.t, Delay030.Wm(:, 4), 'LineWidth', line_width);
plot(Delay035.t, Delay035.Wm(:, 4), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, Delay040.Wm(:, 4), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, Delay045.Wm(:, 4), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, Delay050.Wm(:, 4), 'LineWidth', line_width, 'LineStyle', '-.');
ylim([0, 4]);
ylabel('$\omega_4^2$ $($rad/s$)^2$', 'Interpreter', 'latex', 'FontSize', font_size);
xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
print(PropCmprsnPlot, 'image/time_delay/fig_prop_comparison_td', '-dpng', '-r600');

FlareCmprsnPlot = figure();
FlareCmprsnPlot.Theme = 'light';
FlareCmprsnPlot.Position(3:4) = control_size;
subplot(4, 1, 1);
hold on; grid on;
index_00 = plot(noDelay.t, rad2deg(noDelay.Alpha(:, 1)), 'LineWidth', line_width);
index_05 = plot(Delay005.t, rad2deg(Delay005.Alpha(:, 1)), 'LineWidth', line_width);
index_10 = plot(Delay010.t, rad2deg(Delay010.Alpha(:, 1)), 'LineWidth', line_width);
index_15 = plot(Delay015.t, rad2deg(Delay015.Alpha(:, 1)), 'LineWidth', line_width);
index_20 = plot(Delay020.t, rad2deg(Delay020.Alpha(:, 1)), 'LineWidth', line_width);
index_25 = plot(Delay025.t, rad2deg(Delay025.Alpha(:, 1)), 'LineWidth', line_width);
index_30 = plot(Delay030.t, rad2deg(Delay030.Alpha(:, 1)), 'LineWidth', line_width);
index_35 = plot(Delay035.t, rad2deg(Delay035.Alpha(:, 1)), 'LineWidth', line_width, 'LineStyle', '-.');
index_40 = plot(Delay040.t, rad2deg(Delay040.Alpha(:, 1)), 'LineWidth', line_width, 'LineStyle', '-.');
index_45 = plot(Delay045.t, rad2deg(Delay045.Alpha(:, 1)), 'LineWidth', line_width, 'LineStyle', '-.');
index_50 = plot(Delay050.t, rad2deg(Delay050.Alpha(:, 1)), 'LineWidth', line_width, 'LineStyle', '-.');
ylabel('$\alpha_1$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(4, 1, 2);
hold on; grid on;
plot(noDelay.t, rad2deg(noDelay.Alpha(:, 2)), 'LineWidth', line_width);
plot(Delay005.t, rad2deg(Delay005.Alpha(:, 2)), 'LineWidth', line_width);
plot(Delay010.t, rad2deg(Delay010.Alpha(:, 2)), 'LineWidth', line_width);
plot(Delay015.t, rad2deg(Delay015.Alpha(:, 2)), 'LineWidth', line_width);
plot(Delay020.t, rad2deg(Delay020.Alpha(:, 2)), 'LineWidth', line_width);
plot(Delay025.t, rad2deg(Delay025.Alpha(:, 2)), 'LineWidth', line_width);
plot(Delay030.t, rad2deg(Delay030.Alpha(:, 2)), 'LineWidth', line_width);
plot(Delay035.t, rad2deg(Delay035.Alpha(:, 2)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, rad2deg(Delay040.Alpha(:, 2)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, rad2deg(Delay045.Alpha(:, 2)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, rad2deg(Delay050.Alpha(:, 2)), 'LineWidth', line_width, 'LineStyle', '-.');
ylabel('$\alpha_2$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(4, 1, 3);
hold on; grid on;
plot(noDelay.t, rad2deg(noDelay.Alpha(:, 3)), 'LineWidth', line_width);
plot(Delay005.t, rad2deg(Delay005.Alpha(:, 3)), 'LineWidth', line_width);
plot(Delay010.t, rad2deg(Delay010.Alpha(:, 3)), 'LineWidth', line_width);
plot(Delay015.t, rad2deg(Delay015.Alpha(:, 3)), 'LineWidth', line_width);
plot(Delay020.t, rad2deg(Delay020.Alpha(:, 3)), 'LineWidth', line_width);
plot(Delay025.t, rad2deg(Delay025.Alpha(:, 3)), 'LineWidth', line_width);
plot(Delay030.t, rad2deg(Delay030.Alpha(:, 3)), 'LineWidth', line_width);
plot(Delay035.t, rad2deg(Delay035.Alpha(:, 3)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, rad2deg(Delay040.Alpha(:, 3)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, rad2deg(Delay045.Alpha(:, 3)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, rad2deg(Delay050.Alpha(:, 3)), 'LineWidth', line_width, 'LineStyle', '-.');
ylabel('$\alpha_3$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(4, 1, 4);
hold on; grid on;
plot(noDelay.t, rad2deg(noDelay.Alpha(:, 4)), 'LineWidth', line_width);
plot(Delay005.t, rad2deg(Delay005.Alpha(:, 4)), 'LineWidth', line_width);
plot(Delay010.t, rad2deg(Delay010.Alpha(:, 4)), 'LineWidth', line_width);
plot(Delay015.t, rad2deg(Delay015.Alpha(:, 4)), 'LineWidth', line_width);
plot(Delay020.t, rad2deg(Delay020.Alpha(:, 4)), 'LineWidth', line_width);
plot(Delay025.t, rad2deg(Delay025.Alpha(:, 4)), 'LineWidth', line_width);
plot(Delay030.t, rad2deg(Delay030.Alpha(:, 4)), 'LineWidth', line_width);
plot(Delay035.t, rad2deg(Delay035.Alpha(:, 4)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, rad2deg(Delay040.Alpha(:, 4)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, rad2deg(Delay045.Alpha(:, 4)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, rad2deg(Delay050.Alpha(:, 4)), 'LineWidth', line_width, 'LineStyle', '-.');
ylabel('$\alpha_4$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
print(FlareCmprsnPlot, 'image/time_delay/fig_flare_comparison_td', '-dpng', '-r600');

TiltMinMax = [-115, 115];
TiltPlotLim = [-130, 130];
TiltCmprsnPlot = figure();
TiltCmprsnPlot.Theme = 'light';
TiltCmprsnPlot.Position(3:4) = control_size;
subplot(4, 1, 1);
hold on; grid on;
index_00 = plot(noDelay.t, rad2deg(noDelay.Beta(:, 1)), 'LineWidth', line_width);
index_05 = plot(Delay005.t, rad2deg(Delay005.Beta(:, 1)), 'LineWidth', line_width);
index_10 = plot(Delay010.t, rad2deg(Delay010.Beta(:, 1)), 'LineWidth', line_width);
index_15 = plot(Delay015.t, rad2deg(Delay015.Beta(:, 1)), 'LineWidth', line_width);
index_20 = plot(Delay020.t, rad2deg(Delay020.Beta(:, 1)), 'LineWidth', line_width);
index_25 = plot(Delay025.t, rad2deg(Delay025.Beta(:, 1)), 'LineWidth', line_width);
index_30 = plot(Delay030.t, rad2deg(Delay030.Beta(:, 1)), 'LineWidth', line_width);
index_35 = plot(Delay035.t, rad2deg(Delay035.Beta(:, 1)), 'LineWidth', line_width, 'LineStyle', '-.');
index_40 = plot(Delay040.t, rad2deg(Delay040.Beta(:, 1)), 'LineWidth', line_width, 'LineStyle', '-.');
index_45 = plot(Delay045.t, rad2deg(Delay045.Beta(:, 1)), 'LineWidth', line_width, 'LineStyle', '-.');
index_50 = plot(Delay050.t, rad2deg(Delay050.Beta(:, 1)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(noDelay.t, TiltMinMax(1)*ones([length(noDelay.t), 1]), 'r--', 'LineWidth', 1);
plot(noDelay.t, TiltMinMax(2)*ones([length(noDelay.t), 1]), 'r--', 'LineWidth', 1);
ylim([-10, 10]);
ylabel('$\beta_1$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(4, 1, 2);
hold on; grid on;
plot(noDelay.t, rad2deg(noDelay.Beta(:, 2)), 'LineWidth', line_width);
plot(Delay005.t, rad2deg(Delay005.Beta(:, 2)), 'LineWidth', line_width);
plot(Delay010.t, rad2deg(Delay010.Beta(:, 2)), 'LineWidth', line_width);
plot(Delay015.t, rad2deg(Delay015.Beta(:, 2)), 'LineWidth', line_width);
plot(Delay020.t, rad2deg(Delay020.Beta(:, 2)), 'LineWidth', line_width);
plot(Delay025.t, rad2deg(Delay025.Beta(:, 2)), 'LineWidth', line_width);
plot(Delay030.t, rad2deg(Delay030.Beta(:, 2)), 'LineWidth', line_width);
plot(Delay035.t, rad2deg(Delay035.Beta(:, 2)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, rad2deg(Delay040.Beta(:, 2)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, rad2deg(Delay045.Beta(:, 2)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, rad2deg(Delay050.Beta(:, 2)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(noDelay.t, TiltMinMax(1)*ones([length(noDelay.t), 1]), 'r--', 'LineWidth', 1);
plot(noDelay.t, TiltMinMax(2)*ones([length(noDelay.t), 1]), 'r--', 'LineWidth', 1);
ylim(TiltPlotLim);
ylabel('$\beta_2$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(4, 1, 3);
hold on; grid on;
plot(noDelay.t, rad2deg(noDelay.Beta(:, 3)), 'LineWidth', line_width);
plot(Delay005.t, rad2deg(Delay005.Beta(:, 3)), 'LineWidth', line_width);
plot(Delay010.t, rad2deg(Delay010.Beta(:, 3)), 'LineWidth', line_width);
plot(Delay015.t, rad2deg(Delay015.Beta(:, 3)), 'LineWidth', line_width);
plot(Delay020.t, rad2deg(Delay020.Beta(:, 3)), 'LineWidth', line_width);
plot(Delay025.t, rad2deg(Delay025.Beta(:, 3)), 'LineWidth', line_width);
plot(Delay030.t, rad2deg(Delay030.Beta(:, 3)), 'LineWidth', line_width);
plot(Delay035.t, rad2deg(Delay035.Beta(:, 3)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, rad2deg(Delay040.Beta(:, 3)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, rad2deg(Delay045.Beta(:, 3)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, rad2deg(Delay050.Beta(:, 3)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(noDelay.t, TiltMinMax(1)*ones([length(noDelay.t), 1]), 'r--', 'LineWidth', 1);
plot(noDelay.t, TiltMinMax(2)*ones([length(noDelay.t), 1]), 'r--', 'LineWidth', 1);
ylim(TiltPlotLim);
ylabel('$\beta_3$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(4, 1, 4);
hold on; grid on;
plot(noDelay.t, rad2deg(noDelay.Beta(:, 4)), 'LineWidth', line_width);
plot(Delay005.t, rad2deg(Delay005.Beta(:, 4)), 'LineWidth', line_width);
plot(Delay010.t, rad2deg(Delay010.Beta(:, 4)), 'LineWidth', line_width);
plot(Delay015.t, rad2deg(Delay015.Beta(:, 4)), 'LineWidth', line_width);
plot(Delay020.t, rad2deg(Delay020.Beta(:, 4)), 'LineWidth', line_width);
plot(Delay025.t, rad2deg(Delay025.Beta(:, 4)), 'LineWidth', line_width);
plot(Delay030.t, rad2deg(Delay030.Beta(:, 4)), 'LineWidth', line_width);
plot(Delay035.t, rad2deg(Delay035.Beta(:, 4)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay040.t, rad2deg(Delay040.Beta(:, 4)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay045.t, rad2deg(Delay045.Beta(:, 4)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(Delay050.t, rad2deg(Delay050.Beta(:, 4)), 'LineWidth', line_width, 'LineStyle', '-.');
plot(noDelay.t, TiltMinMax(1)*ones([length(noDelay.t), 1]), 'r--', 'LineWidth', 1);
plot(noDelay.t, TiltMinMax(2)*ones([length(noDelay.t), 1]), 'r--', 'LineWidth', 1);
ylim([-130, 50]);
ylabel('$\beta_4$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
print(TiltCmprsnPlot, 'image/time_delay/fig_tilt_comparison_td', '-dpng', '-r600');


% title('Legend for Tilt Comparison', 'Interpreter', 'latex', 'FontSize', font_size);

% load('logs\morphing_mk2_log_O_mode.mat');
% [pos_n_o, pos_e_o, pos_d_o] = deal(X(:, 1), X(:, 2), X(:, 3));
% [att_r_o, att_p_o, att_y_o] = deal(rad2deg(X(:, 10)), rad2deg(X(:, 11)), rad2deg(X(:, 12)));
% Wm_o = Wm;
% Alpha_o = Alpha;
% Beta_o = Beta;
% load('logs\morphing_mk2_log_H_mode.mat');
% [pos_n_h, pos_e_h, pos_d_h] = deal(X(:, 1), X(:, 2), X(:, 3));
% [att_r_h, att_p_h, att_y_h] = deal(rad2deg(X(:, 10)), rad2deg(X(:, 11)), rad2deg(X(:, 12)));
% Wm_h = Wm;
% Alpha_h = Alpha;
% Beta_h = Beta;
% 
% PosplotOH = figure();
% PosplotOH.Theme = 'light';
% PosplotOH.Position(3:4) = response_size;
% subplot(3, 1, 1);
% subtitle('Position response from X-mode to O and H-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% cmd_pn_plot = plot(t, ref_pn, 'r--');
% res_pn_plot_o = plot(t, pos_n_o, 'Color', plotColor(1,:), 'LineWidth', bold_width);
% res_pn_plot_h = plot(t, pos_n_h, 'Color', plotColor(2,:), 'LineWidth', line_width);
% ylabel('$r_n$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
% legend([cmd_pn_plot, res_pn_plot_o, res_pn_plot_h], {'Command', 'O-mode Response', 'H-mode Response'}, 'Interpreter', 'latex', 'Location', 'southeast');
% subplot(3, 1, 2);
% hold on; grid on;
% plot(t, ref_pe, 'r--');
% plot(t, pos_e_o, 'Color', plotColor(1,:), 'LineWidth', bold_width);
% plot(t, pos_e_h, 'Color', plotColor(2,:), 'LineWidth', line_width);
% ylabel('$r_e$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(3, 1, 3);
% hold on; grid on;
% plot(t, ref_pd, 'r--');
% plot(t, pos_d_o, 'Color', plotColor(1,:), 'LineWidth', bold_width);
% plot(t, pos_d_h, 'Color', plotColor(2,:), 'LineWidth', line_width);
% ylabel('$r_d$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figPositionResponse_oh.png', '-dpng', '-r500');
% 
% AttPlotOH = figure();
% AttPlotOH.Theme = 'light';
% AttPlotOH.Position(3:4) = response_size;
% subplot(3, 1, 1);
% subtitle('Attitude response from X-mode to O and H-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% cmd_r_plot = plot(t, ref_r, 'r--');
% res_r_plot_o = plot(t, att_r_o, 'Color', plotColor(1,:), 'LineWidth', line_width);
% res_r_plot_h = plot(t, att_r_h, 'Color', plotColor(2,:), 'LineWidth', line_width);
% ylabel('$\phi$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% legend([cmd_r_plot, res_r_plot_o, res_r_plot_h], {'Command', 'O-mode Response', 'H-mode Response'}, 'Interpreter', 'latex', 'Location', 'northeast');
% subplot(3, 1, 2);
% hold on; grid on;
% plot(t, ref_p, 'r--');
% plot(t, att_p_o, 'Color', plotColor(1,:), 'LineWidth', line_width);
% plot(t, att_p_h, 'Color', plotColor(2,:), 'LineWidth', line_width);
% ylabel('$\theta$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(3, 1, 3);
% hold on; grid on;
% plot(t, ref_y, 'r--');
% plot(t, att_y_o, 'Color', plotColor(1,:), 'LineWidth', line_width);
% plot(t, att_y_h, 'Color', plotColor(2,:), 'LineWidth', line_width);
% ylabel('$\psi$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figAttitudeResponse_oh.png', '-dpng', '-r500');
% 
% PropPlotOH = figure();
% PropPlotOH.Theme = 'light';
% PropPlotOH.Position(3:4) = control_size;
% subplot(4, 1, 1);
% subtitle('Rotor Angular Speed of O and H-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% wm_plot_o = plot(t, Wm_o(:, 1), 'LineWidth', line_width);
% wm_plot_h = plot(t, Wm_h(:, 1), 'LineWidth', line_width);
% ylabel('$\omega_1^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% legend([wm_plot_o, wm_plot_h], {'O-mode', 'H-mode'}, 'Interpreter', 'latex', 'Location', 'northeast');
% subplot(4, 1, 2);
% hold on; grid on;
% plot(t, Wm_o(:, 2), 'LineWidth', line_width);
% plot(t, Wm_h(:, 2), 'LineWidth', line_width);
% ylabel('$\omega_2^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 3);
% hold on; grid on;
% plot(t, Wm_o(:, 3), 'LineWidth', line_width);
% plot(t, Wm_h(:, 3), 'LineWidth', line_width);
% ylabel('$\omega_3^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 4);
% hold on; grid on;
% plot(t, Wm_o(:, 4), 'LineWidth', line_width);
% plot(t, Wm_h(:, 4), 'LineWidth', line_width);
% ylabel('$\omega_4^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figRotorAngularSpeed_oh.png', '-dpng', '-r500');
% 
% FlarePlotOH = figure();
% FlarePlotOH.Theme = 'light';
% FlarePlotOH.Position(3:4) = control_size;
% subplot(4, 1, 1);
% subtitle('Flare angles of O and H-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% alpha_o_plot = plot(t, rad2deg(Alpha_o(:, 1)), 'LineWidth', line_width);
% alpha_h_plot = plot(t, rad2deg(Alpha_h(:, 1)), '--', 'LineWidth', line_width);
% ylabel('$\alpha_1$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% legend([alpha_o_plot, alpha_h_plot], {'O-mode', 'H-mode'}, 'Interpreter', 'latex', 'Location', 'northeast');
% subplot(4, 1, 2);
% hold on; grid on;
% plot(t, rad2deg(Alpha_o(:, 2)), 'LineWidth', line_width);
% plot(t, rad2deg(Alpha_h(:, 2)), '--', 'LineWidth', line_width);
% ylabel('$\alpha_2$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 3);
% hold on; grid on;
% plot(t, rad2deg(Alpha_o(:, 3)), 'LineWidth', line_width);
% plot(t, rad2deg(Alpha_h(:, 3)), '--', 'LineWidth', line_width);
% ylabel('$\alpha_3$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 4);
% hold on; grid on;
% plot(t, rad2deg(Alpha_o(:, 4)), 'LineWidth', line_width);
% plot(t, rad2deg(Alpha_h(:, 4)), '--', 'LineWidth', line_width);
% ylabel('$\alpha_4$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figFlareAngles_oh.png', '-dpng', '-r500');
% 
% TiltPlotOH = figure();
% TiltPlotOH.Theme = 'light';
% TiltPlotOH.Position(3:4) = control_size;
% subplot(4, 1, 1);
% subtitle('Tilt angles of O and H-mode', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% beta_o_plot = plot(t, rad2deg(Beta_o(:, 1)), 'LineWidth', line_width);
% beta_h_plot = plot(t, rad2deg(Beta_h(:, 1)), 'LineWidth', line_width);
% ylabel('$\beta_1$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% legend([beta_o_plot, beta_h_plot], {'O-mode', 'H-mode'}, 'Interpreter', 'latex', 'Location', 'northeast');
% subplot(4, 1, 2);
% hold on; grid on;
% plot(t, rad2deg(Beta_o(:, 2)), 'LineWidth', line_width);
% plot(t, rad2deg(Beta_h(:, 2)), 'LineWidth', line_width);
% ylabel('$\beta_2$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 3);
% hold on; grid on;
% plot(t, rad2deg(Beta_o(:, 3)), 'LineWidth', line_width);
% plot(t, rad2deg(Beta_h(:, 3)), 'LineWidth', line_width);
% ylabel('$\beta_3$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 4);
% hold on; grid on;
% plot(t, rad2deg(Beta_o(:, 4)), 'LineWidth', line_width);
% plot(t, rad2deg(Beta_h(:, 4)), 'LineWidth', line_width);
% ylabel('$\beta_4$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figTiltAngles_oh.png', '-dpng', '-r500');
% 
% %%
% load('logs\morphing_mk2_log_Y_mode_nonimal.mat');
% [pos_n_yn, pos_e_yn, pos_d_yn] = deal(X(:, 1), X(:, 2), X(:, 3));
% [att_r_yn, att_p_yn, att_y_yn] = deal(rad2deg(X(:, 10)), rad2deg(X(:, 11)), rad2deg(X(:, 12)));
% Wm_yn = Wm;
% Alpha_yn = Alpha;
% Beta_yn = Beta;
% load('logs\morphing_mk2_log_Y_mode_FT.mat');
% [pos_n_yft, pos_e_yft, pos_d_yft] = deal(X(:, 1), X(:, 2), X(:, 3));
% [att_r_yft, att_p_yft, att_y_yft] = deal(rad2deg(X(:, 10)), rad2deg(X(:, 11)), rad2deg(X(:, 12)));
% Wm_yft = Wm;
% Alpha_yft = Alpha;
% Beta_yft = Beta;
% 
% PosplotYn = figure();
% PosplotYn.Theme = 'light';
% PosplotYn.Position(3:4) = response_size;
% subplot(3, 1, 1);
% subtitle('Position response of Fault Tolerant Control', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% fill([10, 20, 20, 10], [-0.5, -0.5, 2.5, 2.5], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% res_pn_plot_yn = plot(t, pos_n_yn, 'Color', plotColor(2,:), 'LineWidth', line_width);
% res_pn_plot_yft = plot(t, pos_n_yft, 'Color', plotColor(1,:), 'LineWidth', bold_width);
% cmd_pn_plot = plot(t, ref_pn, 'r--');
% ylabel('$r_n$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-0.5, 2.5]);
% legend([cmd_pn_plot, res_pn_plot_yn, res_pn_plot_yft], {'Command', 'Nominal Response', 'FTC Response'}, 'Interpreter', 'latex', 'Location', 'southeast');
% subplot(3, 1, 2);
% hold on; grid on;
% fill([10, 20, 20, 10], [-0.5, -0.5, 3, 3], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, pos_e_yn, 'Color', plotColor(2,:), 'LineWidth', line_width);
% plot(t, pos_e_yft, 'Color', plotColor(1,:), 'LineWidth', bold_width);
% plot(t, ref_pe, 'r--');
% ylabel('$r_e$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-0.5, 3]);
% subplot(3, 1, 3);
% hold on; grid on;
% fill([10, 20, 20, 10], [-2.5, -2.5, 0.5, 0.5], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, pos_d_yn, 'Color', plotColor(2,:), 'LineWidth', line_width);
% plot(t, pos_d_yft, 'Color', plotColor(1,:), 'LineWidth', bold_width);
% plot(t, ref_pd, 'r--');
% ylabel('$r_d$ (m)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-2.5, 0.5]);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figPositionResponse_y.png', '-dpng', '-r500');
% 
% AttPlotYn = figure();
% AttPlotYn.Theme = 'light';
% AttPlotYn.Position(3:4) = response_size;
% subplot(3, 1, 1);
% subtitle('Attitude response of Fault Tolerant Control', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% fill([10, 20, 20, 10], [-2.5, -2.5, 1.5, 1.5], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% res_r_plot_yn = plot(t, att_r_yn, 'Color', plotColor(2, :), 'LineWidth', line_width);
% res_r_plot_yft = plot(t, att_r_yft, 'Color', plotColor(1, :), 'LineWidth', bold_width);
% cmd_r_plot = plot(t, ref_r, 'r--');
% ylabel('$\phi$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-2.5, 1.5]);
% legend([cmd_r_plot, res_r_plot_yn, res_r_plot_yft], {'Command', 'Nominal Response', 'FTC Response'}, 'Interpreter', 'latex', 'Location', 'southwest');
% subplot(3, 1, 2);
% hold on; grid on;
% fill([10, 20, 20, 10], [-12.5, -12.5, 10.5, 10.5], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, att_p_yn, 'Color', plotColor(2, :), 'LineWidth', line_width);
% plot(t, att_p_yft, 'Color', plotColor(1, :), 'LineWidth', bold_width);
% plot(t, ref_p, 'r--');
% ylabel('$\theta$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-12.5, 10.5]);
% subplot(3, 1, 3);
% hold on; grid on;
% fill([10, 20, 20, 10], [-0.5, -0.5, 25, 25], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, att_y_yn, 'Color', plotColor(2, :), 'LineWidth', line_width);
% plot(t, att_y_yft, 'Color', plotColor(1, :), 'LineWidth', bold_width);
% plot(t, ref_y, 'r--');
% ylabel('$\psi$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-0.5, 25]);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figAttitudeResponse_y.png', '-dpng', '-r500');
% 
% prop_range = [-0.3, 2];
% PropPlotYn = figure();
% PropPlotYn.Theme = 'light';
% PropPlotYn.Position(3:4) = control_size;
% subplot(4, 1, 1);
% subtitle('Rotor Angular Speed of Fault Tolerant Control', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% fill([10, 20, 20, 10], [-0.3, -0.3, 2, 2], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% nom_omg = plot(t, Wm_yn(:, 1), 'Color', plotColor(2,:), 'LineWidth', line_width);
% ftc_omg = plot(t, Wm_yft(:, 1), 'Color', plotColor(1,:), 'LineWidth', bold_width);
% ylabel('$\omega_1^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim(prop_range);
% legend([ftc_omg, nom_omg], {'FTC', 'Nominal'}, 'Location', 'northeast');
% subplot(4, 1, 2);
% hold on; grid on;
% fill([10, 20, 20, 10], [-0.3, -0.3, 2, 2], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, Wm_yn(:, 2), 'Color', plotColor(2,:), 'LineWidth', line_width);
% plot(t, Wm_yft(:, 2), 'Color', plotColor(1,:), 'LineWidth', bold_width);
% ylabel('$\omega_2^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim(prop_range);
% subplot(4, 1, 3);
% hold on; grid on;
% fill([10, 20, 20, 10], [-0.3, -0.3, 2, 2], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, Wm_yn(:, 3), 'Color', plotColor(2,:), 'LineWidth', line_width);
% plot(t, Wm_yft(:, 3), 'Color', plotColor(1,:), 'LineWidth', bold_width);
% ylabel('$\omega_3^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim(prop_range);
% subplot(4, 1, 4);
% hold on; grid on;
% fill([10, 20, 20, 10], [-0.3, -0.3, 2, 2], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, Wm_yn(:, 4), 'Color', plotColor(2,:), 'LineWidth', line_width);
% plot(t, Wm_yft(:, 4), 'Color', plotColor(1,:), 'LineWidth', bold_width);
% ylabel('$\omega_4^2$ (rad/s)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim(prop_range);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figRotorAngularSpeed_y.png', '-dpng', '-r500');
% 
% FlarePlotYn = figure();
% FlarePlotYn.Theme = 'light';
% FlarePlotYn.Position(3:4) = control_size;
% subplot(4, 1, 1);
% subtitle('Flare angles of Fault Tolerant Control', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% fill([10, 20, 20, 10], [-1, -1, 1, 1], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% ftc_a = plot(t, rad2deg(Alpha_yft(:, 1)), 'LineWidth', line_width);
% nom_a = plot(t, rad2deg(Alpha_yn(:, 1)), 'LineWidth', bold_width, 'LineStyle', '--');
% ylabel('$\alpha_1$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% legend([ftc_a, nom_a], {'FTC', 'Nominal'}, 'Location', 'northeast');
% subplot(4, 1, 2);
% hold on; grid on;
% fill([10, 20, 20, 10], [-45, -45, 5, 5], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, rad2deg(Alpha_yft(:, 2)), 'LineWidth', line_width);
% plot(t, rad2deg(Alpha_yn(:, 2)), 'LineWidth', bold_width, 'LineStyle', '--');
% ylabel('$\alpha_2$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-45, 5]);
% subplot(4, 1, 3);
% hold on; grid on;
% fill([10, 20, 20, 10], [-1, -1, 1, 1], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, rad2deg(Alpha_yft(:, 3)), 'LineWidth', line_width);
% plot(t, rad2deg(Alpha_yn(:, 3)), 'LineWidth', bold_width, 'LineStyle', '--');
% ylabel('$\alpha_3$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% subplot(4, 1, 4);
% hold on; grid on;
% fill([10, 20, 20, 10], [-5, -5, 45, 45], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, rad2deg(Alpha_yft(:, 4)), 'LineWidth', line_width);
% plot(t, rad2deg(Alpha_yn(:, 4)), 'LineWidth', bold_width, 'LineStyle', '--');
% ylabel('$\alpha_4$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-5, 45]);
% print('image/figFlareAngles_y.png', '-dpng', '-r500');
% 
% TiltPlotYn = figure();
% TiltPlotYn.Theme = 'light';
% TiltPlotYn.Position(3:4) = control_size;
% subplot(4, 1, 1);
% subtitle('Tilt angles of Fault Tolerant Control', 'Interpreter', 'latex', 'FontSize', font_size);
% hold on; grid on;
% fill([10, 20, 20, 10], [-9.5, -9.5, 14, 14], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% nom_beta = plot(t, rad2deg(Beta_yn(:, 1)), 'Color', plotColor(2,:), 'LineWidth', line_width);
% ftc_beta = plot(t, rad2deg(Beta_yft(:, 1)), 'Color', plotColor(1,:), 'LineWidth', bold_width);
% ylabel('$\beta_1$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-9.5, 14]);
% legend([ftc_beta, nom_beta], {'FTC', 'Nominal'}, 'Location', 'northeast');
% subplot(4, 1, 2);
% hold on; grid on;
% fill([10, 20, 20, 10], [-28, -28, 16, 16], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, rad2deg(Beta_yn(:, 2)), 'Color', plotColor(2,:), 'LineWidth', line_width);
% plot(t, rad2deg(Beta_yft(:, 2)), 'Color', plotColor(1,:), 'LineWidth', bold_width);
% ylabel('$\beta_2$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-28, 16]);
% subplot(4, 1, 3);
% hold on; grid on;
% fill([10, 20, 20, 10], [-19, -19, 9.5, 9.5], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, rad2deg(Beta_yn(:, 3)), 'Color', plotColor(2,:), 'LineWidth', line_width);
% plot(t, rad2deg(Beta_yft(:, 3)), 'Color', plotColor(1,:), 'LineWidth', bold_width);
% ylabel('$\beta_3$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-19, 9.5]);
% subplot(4, 1, 4);
% hold on; grid on;
% fill([10, 20, 20, 10], [-38, -38, 13, 13], 'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');
% plot(t, rad2deg(Beta_yn(:, 4)), 'Color', plotColor(2,:), 'LineWidth', line_width);
% plot(t, rad2deg(Beta_yft(:, 4)), 'Color', plotColor(1,:), 'LineWidth', bold_width);
% ylabel('$\beta_4$ (deg)', 'Interpreter', 'latex', 'FontSize', font_size);
% ylim([-38, 13]);
% xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
% print('image/figTiltAngles_y.png', '-dpng', '-r500');
% 

%%
cm_x2o = load('logs/data_cm/morphing_mk2_log_CMdata_O.mat');
cm_x2h = load('logs/data_cm/morphing_mk2_log_CMdata_H.mat');
cm_x2y = load('logs/data_cm/morphing_mk2_log_CMdata_Y.mat');

cz = cos(deg2rad(45));
sz = sin(deg2rad(45));
rot_p2x = [cz, -sz, 0;...
           sz,  cz, 0;...
            0,   0, 1];
m2cm = 100;
cm_x2o.CM = (rot_p2x*(cm_x2o.CM'))'.*m2cm;
cm_x2h.CM = (rot_p2x*(cm_x2h.CM'))'.*m2cm;
cm_x2y.CM = (rot_p2x*(cm_x2y.CM'))'.*m2cm;

CoGplot = figure();
CoGplot.Theme = 'light';
CoGplot.Position(3:4) = response_size;
subplot(2, 1, 1);
hold on; grid on;
plot(cm_x2o.t, cm_x2o.CM(:, 1));
plot(cm_x2h.t, cm_x2h.CM(:, 1));
plot(cm_x2y.t, cm_x2y.CM(:, 1));
ylabel('CoG $r_x$ (cm)', 'Interpreter', 'latex', 'FontSize', font_size);
subplot(2, 1, 2);
hold on; grid on;
plot(cm_x2o.t, cm_x2o.CM(:, 2));
plot(cm_x2h.t, cm_x2h.CM(:, 2));
plot(cm_x2y.t, cm_x2y.CM(:, 2));
ylabel('CoG $r_y$ (cm)', 'Interpreter', 'latex', 'FontSize', font_size);
xlabel('time (s)', 'Interpreter', 'latex', 'FontSize', font_size);
